package com.tndmadman.rts;

import java.io.InputStream;
import java.net.ServerSocket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Predicate;
import java.util.zip.ZipFile;

/** End-to-end release gate for a directory generated by the actual v1.6.0 code. */
public final class V160UpgradeValidator {
    private V160UpgradeValidator() { }

    public static void main(String[] args) throws Exception {
        if (args.length != 1) throw new IllegalArgumentException("Expected generated v1.6.0 fixture directory.");
        Path fixture = Path.of(args[0]).toAbsolutePath().normalize();
        Map<String,String> sourceHashes = hashes(fixture);
        Map<String,Object> manifest = object(MiniJson.parse(Files.readString(fixture.resolve("fixture-manifest.json"))));
        require("1.6.0".equals(text(manifest.get("sourceVersion"))), "fixture version is not v1.6.0");
        require("e83df3158d583b8036a80ee9cd1e866cfc2491e3".equals(text(manifest.get("sourceCommit"))),
                "fixture was not built from the published v1.6.0 commit");
        verifyFiles(fixture, list(manifest.get("files")));

        Path work = Files.createTempDirectory("starchem-v160-upgrade-");
        String oldStore = System.getProperty("starchem.sessionStore");
        String oldMode = System.getProperty("starchem.credentialVault");
        String oldVault = System.getProperty("starchem.credentialVaultPath");
        try {
            copyTree(fixture, work);
            validate(work, manifest);
            require(sourceHashes.equals(hashes(fixture)), "upgrade test modified its source fixture");
            System.out.println("StarChem v1.6.0 to v1.7.0 upgrade validation passed.");
        } finally {
            restore("starchem.sessionStore", oldStore);
            restore("starchem.credentialVault", oldMode);
            restore("starchem.credentialVaultPath", oldVault);
            PendingPlayerPassword.clearAll();
            ClientCredentialVault.resetForTests();
            deleteTree(work);
        }
    }

    private static void validate(Path root, Map<String,Object> manifest) throws Exception {
        Path serverDir = root.resolve("server");
        Path clientDir = root.resolve("client");
        Path store = clientDir.resolve("sessions.properties");
        Path vault = clientDir.resolve("credentials");
        String saveName = text(manifest.get("saveName"));
        String fingerprint = text(manifest.get("tlsFingerprint"));
        List<Player> players = players(manifest.get("players"));
        Player alpha = players.get(0), beta = players.get(1);
        Path current = serverDir.resolve(saveName + "-current.starchem-save");
        require(Files.isRegularFile(current) && Files.isRegularFile(serverDir.resolve(saveName + "-previous.starchem-save")),
                "v1.6 current/previous saves are missing");
        try (var files = Files.list(serverDir)) {
            require(files.anyMatch(path -> path.getFileName().toString().matches(saveName + "-\\d{8}-\\d{6}\\.starchem-save")),
                    "v1.6 timestamped backup is missing");
        }
        rejectExtractedDigests(current, alpha);

        System.setProperty("starchem.sessionStore", store.toString());
        System.setProperty("starchem.credentialVault", "file");
        System.setProperty("starchem.credentialVaultPath", vault.toString());
        ClientCredentialVault.resetForTests();
        Config legacy = Config.join(alpha.name, "127.0.0.1", ((Number)manifest.get("legacyPort")).intValue(), false);
        SessionTokenStore.StoredSession remembered = SessionTokenStore.load(legacy);
        require(remembered.valid() && alpha.id.equals(remembered.playerId()) && alpha.currentToken.equals(remembered.token()),
                "v1.6 remembered sign-in did not migrate");
        require(fingerprint.equalsIgnoreCase(SessionTokenStore.serverFingerprint(legacy)), "v1.6 TLS trust did not migrate");
        assertMetadataSanitized(clientDir, players);
        require(Files.isDirectory(vault), "protected client credential vault was not created");

        int port = freePort();
        Config serverConfig = Config.dedicatedServer(text(manifest.get("serverName")), port, false, false, Set.of(),
                StarSystems.DEFAULT_SYSTEM_ID, "", 1, serverDir, saveName, 0, 6, false);
        HeadlessGameServer server = HeadlessGameServer.start(serverConfig);
        try {
            assertState(server, manifest, players);
            require(fingerprint.equalsIgnoreCase(TlsIdentity.serverFingerprint(serverConfig)), "TLS fingerprint changed during upgrade");
            require(Files.isRegularFile(serverDir.resolve(saveName + "-tls.password")), "TLS password file was not created");
            require(Files.readString(serverDir.resolve(saveName + "-admin.json")).contains("v1.6 fixture MOTD"),
                    "administration companion state was lost");
            require(Files.readString(serverDir.resolve(saveName + "-observations.json")).contains(alpha.id),
                    "observation companion state was lost");
            List<String> fixtureEvents = new ServerEventJournal(serverDir, saveName)
                    .lines(20, "FIXTURE", alpha.id);
            require(fixtureEvents.stream().anyMatch(line -> line.contains("synthetic v1.6 activity")),
                    "activity journal state was lost");
            require(Files.isRegularFile(serverDir.resolve(saveName + "-identities.json")),
                    "identity lifecycle state was not created");

            Config alphaConfig = Config.join(alpha.name, "127.0.0.1", port, false);
            SessionTokenStore.saveServerFingerprint(alphaConfig, fingerprint);
            SessionTokenStore.saveAuthDigest(alphaConfig, PasswordAuth.verifier(alpha.name, alpha.password));
            SessionTokenStore.save(alphaConfig, alpha.id, alpha.currentToken);
            ClientRun first = connect(server, alphaConfig, null);
            String rotated = SessionTokenStore.load(alphaConfig).token();
            disconnect(server, first, alpha.id);
            require(!rotated.equals(alpha.currentToken), "current v1.6 token was not rotated");
            PersistentPlayerSession alphaSession = session(server.network.persistentPlayerSessions(), alpha.id);
            require(PasswordAuth.sessionTokenMatches(alphaSession.previousTokenDigest(), alpha.currentToken),
                    "fresh previous-token grace state was not retained");

            SessionTokenStore.save(alphaConfig, alpha.id, alpha.currentToken);
            ClientRun second = connect(server, alphaConfig, null);
            disconnect(server, second, alpha.id);
            alphaSession = session(server.network.persistentPlayerSessions(), alpha.id);
            require(!PasswordAuth.sessionTokenMatches(alphaSession.tokenDigest(), alpha.currentToken)
                            && !PasswordAuth.sessionTokenMatches(alphaSession.previousTokenDigest(), alpha.currentToken),
                    "consumed v1.6 token remained valid after second rotation");

            Config betaConfig = Config.join(beta.name, "127.0.0.1", port, false);
            SessionTokenStore.clear(betaConfig);
            ClientRun betaRun = connect(server, betaConfig, beta.password);
            require(beta.id.equals(betaRun.network.localPlayerId()), "password reclaim selected the wrong retained identity");
            disconnect(server, betaRun, beta.id);
            require(PasswordAuth.passwordVersion(session(server.network.persistentPlayerSessions(), beta.id).passwordSalt())
                    == PasswordAuth.AUTH_VERSION_V2, "legacy password identity was not upgraded");

            ServerShutdownResult stop = server.stop();
            require(stop.clean(), "upgraded server did not stop cleanly: " + stop.message());
            ServerSaveStore.validateArchive(current);
        } finally {
            if (server.running()) server.forceStop();
        }

        HeadlessGameServer restarted = HeadlessGameServer.start(serverConfig);
        try {
            assertState(restarted, manifest, players);
            require(fingerprint.equalsIgnoreCase(TlsIdentity.serverFingerprint(serverConfig)), "TLS fingerprint changed after restart");
        } finally {
            require(restarted.stop().clean(), "restarted upgraded server did not stop cleanly");
        }
        assertMetadataSanitized(clientDir, players);
    }

    private static void assertState(HeadlessGameServer server, Map<String,Object> manifest, List<Player> players) {
        List<PersistentPlayerSession> sessions = server.network.persistentPlayerSessions();
        for (Player player : players) {
            PersistentPlayerSession saved = session(sessions, player.id);
            require(player.name.equals(saved.name()), "retained identity name changed for " + player.id);
            require(server.world.hasLiveAssets(player.id), "live assets were lost for " + player.id);
            require(server.world.hasResearch(player.id, "advanced_industry"), "research was lost for " + player.id);
        }
        require(server.world.galaxyMapSnapshot().systems().size() >= ((Number)manifest.get("systemCount")).intValue(),
                "galaxy systems were lost");
        require(list(server.world.captureServerSaveRuntime().get("npcFactions")).size()
                        >= ((Number)manifest.get("npcRuntimeCount")).intValue(), "NPC runtime state was lost");
        require(materialAcrossAssets(server.world, players.get(0).id, Material.COPPER) >= 210.0 - 0.001,
                "alpha inventory was lost");
        require(anyBase(server.world, players.get(0).id,
                        base -> base.productionQueue.size() == 1),
                "alpha production queue was lost");
        require(materialAcrossAssets(server.world, players.get(1).id, Material.SILICATES) >= 321.0 - 0.001,
                "beta cross-system inventory was lost");
    }

    private static double materialAcrossAssets(World world, String playerId, Material material) {
        String active = world.activeSystemId();
        double total = 0;
        try {
            for (GalaxyMapSystem system : world.galaxyMapSnapshot().systems()) {
                world.activateSystem(system.id());
                for (Base base : world.bases.values()) {
                    if (playerId.equals(base.playerId)) {
                        total += base.inventory.getOrDefault(material, 0.0);
                    }
                }
                for (Unit unit : world.units.values()) {
                    if (playerId.equals(unit.playerId)) {
                        total += unit.inventory.getOrDefault(material, 0.0);
                    }
                }
            }
            return total;
        } finally {
            world.activateSystem(active);
        }
    }

    private static boolean anyBase(World world, String playerId, Predicate<Base> expected) {
        String active = world.activeSystemId();
        try {
            for (GalaxyMapSystem system : world.galaxyMapSnapshot().systems()) {
                world.activateSystem(system.id());
                for (Base base : world.bases.values()) {
                    if (playerId.equals(base.playerId) && expected.test(base)) return true;
                }
            }
            return false;
        } finally {
            world.activateSystem(active);
        }
    }

    private static ClientRun connect(HeadlessGameServer server, Config config, String password) throws Exception {
        if (password != null) PendingPlayerPassword.remember(config, password.toCharArray(), false);
        World world = new World(config.playerName, Set.of(), StarSystems.DEFAULT_SYSTEM_ID, false);
        PeerNetwork network = PeerNetwork.start(config, world);
        ClientRun run = new ClientRun(network);
        long deadline = System.currentTimeMillis() + 20_000;
        while (!(network.clientConnected() && network.clientReady()) && System.currentTimeMillis() < deadline) tick(server, run);
        require(network.clientConnected() && network.clientReady(), "client authentication failed: " + network.failureMessage());
        return run;
    }

    private static void disconnect(HeadlessGameServer server, ClientRun run, String playerId) throws Exception {
        run.network.shutdown();
        long deadline = System.currentTimeMillis() + 8_000;
        while (server.network.serverSessionConnected(playerId) && System.currentTimeMillis() < deadline) {
            server.tick(0.016); Thread.sleep(4);
        }
        require(!server.network.serverSessionConnected(playerId), "client remained connected: " + playerId);
    }

    private static void tick(HeadlessGameServer server, ClientRun run) throws Exception {
        server.tick(0.016); run.network.tick(); Thread.sleep(4);
    }

    private static void rejectExtractedDigests(Path save, Player player) throws Exception {
        try (ZipFile zip = new ZipFile(save.toFile(), StandardCharsets.UTF_8)) {
            try (InputStream input = zip.getInputStream(zip.getEntry("players.json"))) {
                Map<String,Object> players = object(MiniJson.parse(new String(input.readAllBytes(), StandardCharsets.UTF_8)));
                Map<String,Object> row = list(players.get("sessions")).stream().map(V160UpgradeValidator::object)
                        .filter(item -> player.id.equals(text(item.get("playerId")))).findFirst().orElseThrow();
                byte[] passwordDigest = PasswordAuth.decodeVerifier(text(row.get("passwordVerifierSha256")));
                byte[] salt = PasswordAuth.digestSalt(PasswordAuth.decodeHex(text(row.get("passwordSalt"))));
                require(!PasswordAuth.passwordCredentialMatches(passwordDigest, passwordDigest, salt),
                        "save-extracted password digest authenticated");
                byte[] tokenDigest = Base64.getUrlDecoder().decode(text(row.get("tokenDigestSha256")));
                require(!PasswordAuth.sessionTokenMatches(tokenDigest,
                        Base64.getUrlEncoder().withoutPadding().encodeToString(tokenDigest)),
                        "save-extracted token digest authenticated");
            }
        }
    }

    private static void assertMetadataSanitized(Path clientDir, List<Player> players) throws Exception {
        for (String name : List.of("sessions.properties", "sessions.properties.previous")) {
            Path path = clientDir.resolve(name);
            if (!Files.isRegularFile(path)) continue;
            String text = Files.readString(path, StandardCharsets.ISO_8859_1);
            for (Player player : players) require(!text.contains(player.currentToken)
                    && !text.contains(PasswordAuth.verifier(player.name, player.password)),
                    "plaintext credential remained in " + name);
        }
    }

    private static PersistentPlayerSession session(List<PersistentPlayerSession> sessions, String id) {
        return sessions.stream().filter(value -> id.equals(value.playerId())).findFirst()
                .orElseThrow(() -> new IllegalStateException("retained session missing: " + id));
    }

    private static List<Player> players(Object value) {
        List<Player> out = new ArrayList<>();
        for (Object item : list(value)) {
            Map<String,Object> row = object(item);
            out.add(new Player(text(row.get("id")), text(row.get("name")), text(row.get("password")),
                    text(row.get("currentToken")), text(row.get("previousToken"))));
        }
        return out;
    }

    private static void verifyFiles(Path root, List<Object> rows) throws Exception {
        for (Object item : rows) {
            Map<String,Object> row = object(item);
            Path path = root.resolve(text(row.get("path"))).normalize();
            require(path.startsWith(root) && Files.isRegularFile(path), "fixture file missing: " + path);
            String hash = HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(path)));
            require(hash.equalsIgnoreCase(text(row.get("sha256"))), "fixture hash changed: " + path);
        }
    }

    private static Map<String,String> hashes(Path root) throws Exception {
        Map<String,String> out = new LinkedHashMap<>();
        try (var paths = Files.walk(root)) {
            for (Path path : paths.filter(Files::isRegularFile).sorted().toList()) out.put(
                    root.relativize(path).toString(), HexFormat.of().formatHex(
                            MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(path))));
        }
        return out;
    }

    private static void copyTree(Path source, Path target) throws Exception {
        try (var paths = Files.walk(source)) {
            for (Path path : paths.sorted().toList()) {
                Path destination = target.resolve(source.relativize(path).toString());
                if (Files.isDirectory(path)) Files.createDirectories(destination);
                else Files.copy(path, destination, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.COPY_ATTRIBUTES);
            }
        }
    }

    private static int freePort() throws Exception { try (ServerSocket socket = new ServerSocket(0)) { return socket.getLocalPort(); } }
    @SuppressWarnings("unchecked") private static Map<String,Object> object(Object value) { return value instanceof Map<?,?> map ? (Map<String,Object>)map : new LinkedHashMap<>(); }
    @SuppressWarnings("unchecked") private static List<Object> list(Object value) { return value instanceof List<?> list ? (List<Object>)list : List.of(); }
    private static String text(Object value) { return value == null ? "" : String.valueOf(value); }
    private static void restore(String key, String value) { if (value == null) System.clearProperty(key); else System.setProperty(key, value); }
    private static void deleteTree(Path root) { try (var paths = Files.walk(root)) { paths.sorted(Comparator.reverseOrder()).forEach(path -> { try { Files.deleteIfExists(path); } catch (Exception ignored) { } }); } catch (Exception ignored) { } }
    private static void require(boolean condition, String message) { if (!condition) throw new IllegalStateException(message); }

    private record Player(String id, String name, String password, String currentToken, String previousToken) { }
    private record ClientRun(PeerNetwork network) { }
}
