package com.tndmadman.rts;

import java.net.ServerSocket;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Predicate;
import java.util.stream.Stream;

/** End-to-end release gate for state generated by the exact published v1.7.0 code. */
public final class V170UpgradeValidator {
    private static final String SOURCE_COMMIT = "71bf62d1eb6a35e747ad9b494fded32b6e5e57fb";
    private static final int SOURCE_SAVE_FORMAT = 2;
    private static final int SOURCE_PROTOCOL = 8;
    private static final int SOURCE_RULES = 14;

    private V170UpgradeValidator() { }

    public static void main(String[] args) throws Exception {
        if (args.length != 1) throw new IllegalArgumentException("Expected generated v1.7.0 fixture directory.");
        Path fixture = Path.of(args[0]).toAbsolutePath().normalize();
        Map<String,String> sourceHashes = hashes(fixture);
        Map<String,Object> manifest = object(MiniJson.parse(Files.readString(fixture.resolve("fixture-manifest.json"))));
        require("1.7.0".equals(text(manifest.get("sourceVersion"))), "fixture version is not v1.7.0");
        require(SOURCE_COMMIT.equals(text(manifest.get("sourceCommit"))),
                "fixture was not built from the published v1.7.0 commit");
        require(number(manifest.get("sourceSaveFormat")) == SOURCE_SAVE_FORMAT, "fixture save format is not v2");
        require(number(manifest.get("sourceProtocol")) == SOURCE_PROTOCOL, "fixture protocol is not v8");
        require(number(manifest.get("sourceRulesVersion")) == SOURCE_RULES, "fixture rules version is not v14");
        require(ServerSaveStore.SAVE_FORMAT_VERSION >= 6, "current server save format unexpectedly predates v6");
        require(MultiplayerCompatibility.PROTOCOL_VERSION >= 17, "current protocol unexpectedly predates v17");
        verifyFiles(fixture, list(manifest.get("files")));

        Path work = Files.createTempDirectory("starchem-v170-upgrade-");
        String oldStore = System.getProperty("starchem.sessionStore");
        String oldMode = System.getProperty("starchem.credentialVault");
        String oldVault = System.getProperty("starchem.credentialVaultPath");
        try {
            copyTree(fixture, work);
            validate(work, manifest);
            require(sourceHashes.equals(hashes(fixture)), "upgrade validation modified its source fixture");
            System.out.println("StarChem v1.7.0 to current upgrade validation passed.");
        } finally {
            restore("starchem.sessionStore", oldStore);
            restore("starchem.credentialVault", oldMode);
            restore("starchem.credentialVaultPath", oldVault);
            PendingPlayerPassword.clearAll();
            ClientCredentialVault.resetForTests();
            deleteTree(work);
        }
    }

    private static void validate(Path root, Map<String,Object> manifest) throws Exception {
        Path serverDir = root.resolve("server");
        Path clientDir = root.resolve("client");
        String saveName = text(manifest.get("saveName"));
        String fingerprint = text(manifest.get("tlsFingerprint"));
        List<Player> players = players(manifest.get("players"));
        Player alpha = players.get(0);
        Player beta = players.get(1);
        Path current = serverDir.resolve(saveName + "-current.starchem-save");
        Path previous = serverDir.resolve(saveName + "-previous.starchem-save");

        require(Files.isRegularFile(current), "v1.7 current save is missing");
        require(Files.isRegularFile(previous), "v1.7 previous save is missing");
        require(ServerSaveStore.validateArchive(current).version() == SOURCE_SAVE_FORMAT,
                "source current save is not format 2");
        require(ServerSaveStore.validateArchive(previous).version() == SOURCE_SAVE_FORMAT,
                "source previous save is not format 2");
        try (Stream<Path> files = Files.list(serverDir)) {
            require(files.anyMatch(path -> path.getFileName().toString().matches(saveName + "-\\d{8}-\\d{6}\\.starchem-save")),
                    "v1.7 timestamped backup is missing");
        }

        System.setProperty("starchem.sessionStore", clientDir.resolve("sessions.properties").toString());
        System.setProperty("starchem.credentialVault", "file");
        System.setProperty("starchem.credentialVaultPath", clientDir.resolve("credentials").toString());
        ClientCredentialVault.resetForTests();

        Config legacyClient = Config.join(alpha.name, "127.0.0.1", number(manifest.get("legacyPort")), false);
        SessionTokenStore.StoredSession remembered = SessionTokenStore.load(legacyClient);
        require(remembered.valid() && alpha.id.equals(remembered.playerId()) && alpha.currentToken.equals(remembered.token()),
                "v1.7 remembered session did not survive into current credential handling");
        require(fingerprint.equalsIgnoreCase(SessionTokenStore.serverFingerprint(legacyClient)),
                "v1.7 pinned TLS fingerprint did not survive");

        int port = freePort();
        Config serverConfig = Config.dedicatedServer(text(manifest.get("serverName")), port, false, false, Set.of(),
                StarSystems.DEFAULT_SYSTEM_ID, "", 1, serverDir, saveName, 0, 6, false);
        HeadlessGameServer server = HeadlessGameServer.start(serverConfig);
        try {
            assertState(server, manifest, players, true);
            require(fingerprint.equalsIgnoreCase(TlsIdentity.serverFingerprint(serverConfig)),
                    "TLS fingerprint changed while loading v1.7 state");
            require(Files.readString(serverDir.resolve(saveName + "-admin.json")).contains("v1.7 fixture MOTD"),
                    "administration companion state was lost");
            require(Files.readString(serverDir.resolve(saveName + "-observations.json")).contains(alpha.id),
                    "observation companion state was lost");
            require(new ServerEventJournal(serverDir, saveName).lines(20, "FIXTURE", alpha.id).stream()
                            .anyMatch(line -> line.contains("synthetic v1.7 activity")),
                    "activity journal state was lost");

            validateResumeMigration(server, serverConfig, alpha, fingerprint);
            validatePasswordReclaim(server, serverConfig, beta, fingerprint);

            ServerShutdownResult stop = server.stop();
            require(stop.clean(), "upgraded server did not stop cleanly: " + stop.message());
        } finally {
            if (server.running()) server.forceStop();
        }

        ServerSaveStore.ValidatedArchive migrated = ServerSaveStore.validateArchive(current);
        require(migrated.version() == ServerSaveStore.SAVE_FORMAT_VERSION,
                "v1.7 state was not rewritten at the current save format");
        require(number(migrated.manifest().get("saveFormatVersion")) == ServerSaveStore.SAVE_FORMAT_VERSION,
                "migrated manifest reports the wrong save format");

        HeadlessGameServer restarted = HeadlessGameServer.start(serverConfig);
        try {
            assertState(restarted, manifest, players, false);
            require(fingerprint.equalsIgnoreCase(TlsIdentity.serverFingerprint(serverConfig)),
                    "TLS fingerprint changed after migrated restart");
        } finally {
            require(restarted.stop().clean(), "restarted migrated server did not stop cleanly");
        }
        require(ServerSaveStore.validateArchive(current).version() == ServerSaveStore.SAVE_FORMAT_VERSION,
                "second-generation save did not remain at the current format");
    }

    private static void validateResumeMigration(HeadlessGameServer server, Config serverConfig,
                                                Player player, String fingerprint) throws Exception {
        Config client = Config.join(player.name, "127.0.0.1", serverConfig.port, false);
        SessionTokenStore.saveServerFingerprint(client, fingerprint);
        SessionTokenStore.saveAuthDigest(client, PasswordAuth.verifier(player.name, player.password));
        SessionTokenStore.save(client, player.id, player.currentToken);
        ClientRun first = connect(server, client, null);
        require(player.id.equals(first.network.localPlayerId()), "v1.7 resume selected the wrong retained identity");
        String rotated = SessionTokenStore.load(client).token();
        require(!rotated.isBlank() && !rotated.equals(player.currentToken), "v1.7 resume token was not rotated");
        disconnect(server, first, player.id);
    }

    private static void validatePasswordReclaim(HeadlessGameServer server, Config serverConfig,
                                                Player player, String fingerprint) throws Exception {
        Config client = Config.join(player.name, "127.0.0.1", serverConfig.port, false);
        SessionTokenStore.clear(client);
        SessionTokenStore.saveServerFingerprint(client, fingerprint);
        ClientRun run = connect(server, client, player.password);
        require(player.id.equals(run.network.localPlayerId()), "v1.7 password reclaim selected the wrong retained identity");
        disconnect(server, run, player.id);
    }

    private static void assertState(HeadlessGameServer server, Map<String,Object> manifest,
                                    List<Player> players, boolean requireLegacyQueue) {
        List<PersistentPlayerSession> sessions = server.network.persistentPlayerSessions();
        for (Player player : players) {
            PersistentPlayerSession saved = session(sessions, player.id);
            require(player.name.equals(saved.name()), "retained identity name changed for " + player.id);
            require(server.world.hasLiveAssets(player.id), "live assets were lost for " + player.id);
            require(server.world.hasResearch(player.id, "advanced_industry"), "research was lost for " + player.id);
        }
        require(server.world.galaxyMapSnapshot().systems().size() >= number(manifest.get("systemCount")),
                "galaxy systems were lost");
        require(list(server.world.captureServerSaveRuntime().get("npcFactions")).size()
                        >= number(manifest.get("npcRuntimeCount")), "NPC runtime state was lost");
        require(materialAcrossAssets(server.world, players.get(0).id, Material.COPPER) >= 210.0 - 0.001,
                "alpha inventory was lost");
        require(materialAcrossAssets(server.world, players.get(1).id, Material.SILICATES) >= 321.0 - 0.001,
                "beta cross-system inventory was lost");
        require(allOwnedShipsHaveDefaultLoadouts(server.world, players),
                "legacy v1.7 ships were not assigned valid default loadouts");
        if (requireLegacyQueue) {
            require(anyBase(server.world, players.get(0).id, base -> base.productionQueue.stream().anyMatch(job ->
                            job.kind == ProductionJobKind.SHIP
                                    && Rules.STARTING_SHIP.equals(job.itemId)
                                    && WeaponRules.defaultLoadoutId(job.itemId).equals(job.loadoutId))),
                    "legacy queued ship build did not receive its default loadout");
        } else {
            require(anyBase(server.world, players.get(0).id, base -> base.productionQueue.stream().allMatch(job ->
                            job.kind != ProductionJobKind.SHIP || (job.loadoutId != null && !job.loadoutId.isBlank()))),
                    "migrated production queue contains a ship without a loadout");
        }
    }

    private static boolean allOwnedShipsHaveDefaultLoadouts(World world, List<Player> players) {
        Set<String> ids = players.stream().map(Player::id).collect(java.util.stream.Collectors.toSet());
        String active = world.activeSystemId();
        boolean found = false;
        try {
            for (GalaxyMapSystem system : world.galaxyMapSnapshot().systems()) {
                world.activateSystem(system.id());
                for (Unit unit : world.units.values()) {
                    if (!ids.contains(unit.playerId)) continue;
                    found = true;
                    if (!WeaponRules.defaultLoadoutId(unit.shipTypeId).equals(unit.loadoutId)) return false;
                }
            }
            return found;
        } finally {
            world.activateSystem(active);
        }
    }

    private static double materialAcrossAssets(World world, String playerId, Material material) {
        String active = world.activeSystemId();
        double total = 0;
        try {
            for (GalaxyMapSystem system : world.galaxyMapSnapshot().systems()) {
                world.activateSystem(system.id());
                for (Base base : world.bases.values()) {
                    if (playerId.equals(base.playerId)) total += base.inventory.getOrDefault(material, 0.0);
                }
                for (Unit unit : world.units.values()) {
                    if (playerId.equals(unit.playerId)) total += unit.inventory.getOrDefault(material, 0.0);
                }
            }
            return total;
        } finally {
            world.activateSystem(active);
        }
    }

    private static boolean anyBase(World world, String playerId, Predicate<Base> expected) {
        String active = world.activeSystemId();
        try {
            for (GalaxyMapSystem system : world.galaxyMapSnapshot().systems()) {
                world.activateSystem(system.id());
                for (Base base : world.bases.values()) {
                    if (playerId.equals(base.playerId) && expected.test(base)) return true;
                }
            }
            return false;
        } finally {
            world.activateSystem(active);
        }
    }

    private static ClientRun connect(HeadlessGameServer server, Config config, String password) throws Exception {
        if (password != null) PendingPlayerPassword.remember(config, password.toCharArray(), false);
        World world = new World(config.playerName, Set.of(), StarSystems.DEFAULT_SYSTEM_ID, false);
        PeerNetwork network = PeerNetwork.start(config, world);
        ClientRun run = new ClientRun(network);
        long deadline = System.currentTimeMillis() + 20_000;
        while (!(network.clientConnected() && network.clientReady()) && System.currentTimeMillis() < deadline) {
            server.tick(0.016);
            run.network.tick();
            Thread.sleep(4);
        }
        require(network.clientConnected() && network.clientReady(),
                "client authentication failed: " + network.failureMessage());
        return run;
    }

    private static void disconnect(HeadlessGameServer server, ClientRun run, String playerId) throws Exception {
        run.network.shutdown();
        long deadline = System.currentTimeMillis() + 8_000;
        while (server.network.serverSessionConnected(playerId) && System.currentTimeMillis() < deadline) {
            server.tick(0.016);
            Thread.sleep(4);
        }
        require(!server.network.serverSessionConnected(playerId), "client remained connected: " + playerId);
    }

    private static PersistentPlayerSession session(List<PersistentPlayerSession> sessions, String id) {
        return sessions.stream().filter(value -> id.equals(value.playerId())).findFirst()
                .orElseThrow(() -> new IllegalStateException("retained session missing: " + id));
    }

    private static List<Player> players(Object value) {
        List<Player> out = new ArrayList<>();
        for (Object item : list(value)) {
            Map<String,Object> row = object(item);
            out.add(new Player(text(row.get("id")), text(row.get("name")), text(row.get("password")),
                    text(row.get("currentToken")), text(row.get("previousToken"))));
        }
        require(out.size() >= 2, "fixture player metadata is incomplete");
        return out;
    }

    private static void verifyFiles(Path root, List<Object> rows) throws Exception {
        for (Object item : rows) {
            Map<String,Object> row = object(item);
            Path path = root.resolve(text(row.get("path"))).normalize();
            require(path.startsWith(root) && Files.isRegularFile(path), "fixture file missing: " + path);
            String hash = HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(path)));
            require(hash.equalsIgnoreCase(text(row.get("sha256"))), "fixture hash changed: " + path);
        }
    }

    private static Map<String,String> hashes(Path root) throws Exception {
        Map<String,String> out = new LinkedHashMap<>();
        try (Stream<Path> paths = Files.walk(root)) {
            for (Path path : paths.filter(Files::isRegularFile).sorted().toList()) {
                out.put(root.relativize(path).toString(), HexFormat.of().formatHex(
                        MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(path))));
            }
        }
        return out;
    }

    private static void copyTree(Path source, Path target) throws Exception {
        try (Stream<Path> paths = Files.walk(source)) {
            for (Path path : paths.sorted().toList()) {
                Path destination = target.resolve(source.relativize(path).toString());
                if (Files.isDirectory(path)) Files.createDirectories(destination);
                else Files.copy(path, destination, StandardCopyOption.REPLACE_EXISTING, StandardCopyOption.COPY_ATTRIBUTES);
            }
        }
    }

    private static void deleteTree(Path root) throws Exception {
        if (root == null || !Files.exists(root)) return;
        try (Stream<Path> paths = Files.walk(root)) {
            for (Path path : paths.sorted(Comparator.reverseOrder()).toList()) Files.deleteIfExists(path);
        }
    }

    private static void restore(String key, String value) {
        if (value == null) System.clearProperty(key);
        else System.setProperty(key, value);
    }

    private static int freePort() throws Exception {
        try (ServerSocket socket = new ServerSocket(0)) { return socket.getLocalPort(); }
    }

    @SuppressWarnings("unchecked")
    private static Map<String,Object> object(Object value) {
        return value instanceof Map<?,?> map ? (Map<String,Object>)map : new LinkedHashMap<>();
    }

    @SuppressWarnings("unchecked")
    private static List<Object> list(Object value) {
        return value instanceof List<?> items ? (List<Object>)items : List.of();
    }

    private static String text(Object value) { return value == null ? "" : value.toString(); }
    private static int number(Object value) { return value instanceof Number n ? n.intValue() : -1; }

    private static void require(boolean condition, String message) {
        if (!condition) throw new IllegalStateException(message);
    }

    private record Player(String id, String name, String password, String currentToken, String previousToken) { }
    private record ClientRun(PeerNetwork network) { }
}
